import re
from typing import Dict, Any, List

class GovernanceGuardrails:
    """
    Ensures that SQL generated by Conversational Analytics strictly adheres to:
    1. Governed Semantic Gold views (no raw bronze direct joins).
    2. Zero unauthorized schema access (DROP, TRUNCATE, ALTER, INSERT, UPDATE, DELETE).
    3. Mathematical metric formula integrity without grain mismatch.
    4. Anti-hallucination validation against the Snowflake Semantic Model.
    """
    ALLOWED_VIEWS = [
        'VS_GOLD_SUPPLY_CHAIN_UNIFIED_METRICS',
        'VS_GOLD_INVENTORY_LEDGER_METRICS',
        'VS_GOLD_REVERSE_LOGISTICS_METRICS',
        'DIM_PRODUCTS',
        'DIM_FACTORIES',
        'DIM_RDC'
    ]

    DISALLOWED_KEYWORDS = [
        'DROP ', 'DELETE ', 'UPDATE ', 'INSERT ', 'ALTER ', 'TRUNCATE ', 'GRANT ', 'REVOKE ',
        'INFORMATION_SCHEMA', 'PRAGMA', 'EXEC', 'SYSTEM$'
    ]

    @classmethod
    def validate_sql(cls, sql_query: str) -> Dict[str, Any]:
        upper_sql = sql_query.upper().strip()
        
        # 1. Block destructive operations
        for bad_kw in cls.DISALLOWED_KEYWORDS:
            if bad_kw in upper_sql:
                return {
                    "is_valid": False,
                    "reason": f"SECURITY_VIOLATION: Disallowed keyword '{bad_kw.strip()}' detected. Conversational layer is strictly read-only."
                }

        # 2. Enforce Governed Gold Semantic Views
        table_found = False
        for allowed in cls.ALLOWED_VIEWS:
            if allowed in upper_sql:
                table_found = True
                break
                
        if not table_found:
            return {
                "is_valid": False,
                "reason": "GOVERNANCE_VIOLATION: Query must reference governed gold semantic views (e.g. VS_GOLD_SUPPLY_CHAIN_UNIFIED_METRICS) rather than raw unverified tables."
            }

        # 3. Check for SQL Injection & Multiple Statements
        if ';' in sql_query.rstrip(';'):
            return {
                "is_valid": False,
                "reason": "SECURITY_VIOLATION: Multiple SQL statement chaining is blocked by governance guardrails."
            }

        return {"is_valid": True, "reason": "Query conforms to all enterprise governance guardrails."}

guardrails = GovernanceGuardrails()
